@admin_token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJmcmVzaCI6ZmFsc2UsImlhdCI6MTc0NTMyMjMwOSwianRpIjoiZGEzMjdkMmUtMGUwZC00NzdmLTlhOGItZjM4OGY3ZmE3Y2IzIiwidHlwZSI6ImFjY2VzcyIsInN1YiI6IjEiLCJuYmYiOjE3NDUzMjIzMDksImV4cCI6MTc0NTMyOTUwOX0.WLLUjrYCgaD8AIOLL54heFfZyrQNsRSZDjMTpgY8OrU
@school_token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJmcmVzaCI6ZmFsc2UsImlhdCI6MTc0NTMyMjMyNiwianRpIjoiOTQ2NjNlYTgtZjNkZS00MTEyLTllYjEtNDU2N2Y4ZWRkZGZkIiwidHlwZSI6ImFjY2VzcyIsInN1YiI6IjIiLCJuYmYiOjE3NDUzMjIzMjYsImV4cCI6MTc0NTMyOTUyNn0.uUrnpqcUF2OtIBX4UjfShk8fG8G70K3cNhpJv6rwymg

### 🔐 Login admin
POST http://127.0.0.1:5000/api/auth/login
Content-Type: application/json

{
  "username": "admin",
  "password": "123"
}

###

### 🔐 Login school user
POST http://127.0.0.1:5000/api/auth/login
Content-Type: application/json

{
  "username": "ad1",
  "password": "123"
}

###

### 👤 Lấy thông tin người dùng //ok
GET http://127.0.0.1:5000/api/user/me
Authorization: Bearer {{school_token}}

###

### 🏫 Lấy danh sách trường học //ok
GET http://127.0.0.1:5000/api/school/
Authorization: Bearer {{admin_token}}

###

### 📟 Tạo thiết bị mới // đã ok
POST http://127.0.0.1:5000/api/device/create
Content-Type: application/json
Authorization: Bearer {{admin_token}}

{
  "name": "ESP32-KhuA",
  "ip_address": "192.168.1.3",
  "mac_address": "00:1A:2B:3C:4D:5A",
  "school_id": 4,
  "user_id": 4
}

###

### 📟 Danh sách thiết bị //ok
GET http://127.0.0.1:5000/api/device/list
Authorization: Bearer {{admin_token}}

###

### 🕰️ Danh sách lịch chuông //ok
GET http://127.0.0.1:5000/api/schedule/
Authorization: Bearer {{school_token}}

###

### ➕ Tạo lịch chuông //ok
POST http://127.0.0.1:5000/api/schedule/
Content-Type: application/json
Authorization: Bearer {{school_token}}

{
  "day_of_week": 2,
  "start_time": "10:00",
  "end_time": "10:15",
  "bell_type": "Ra chơi",
  "is_summer": false
}

###

### 📝 Sửa lịch chuông //ok 
PUT http://127.0.0.1:5000/api/schedule/2
Content-Type: application/json
Authorization: Bearer {{school_token}}

{
  "day_of_week": 1,
  "start_time": "10:20",
  "end_time": "10:35",
  "bell_type": "Điểm tiết",
  "is_summer": false
}

###

### ❌ Xoá lịch chuông //ok 
DELETE http://127.0.0.1:5000/api/schedule/36
Authorization: Bearer {{school_token}}

###

### 📅 Tạo ngày nghỉ //tạm ok 
POST http://127.0.0.1:5000/api/holiday/
Content-Type: application/json
Authorization: Bearer {{admin_token}}

{
  "name": "Nghỉ 24",
  "start_date": "2028-06-30",
  "end_date": "2028-07-03"
}

###

### 📅 Lấy Danh sách ngày nghỉ //ok
GET http://127.0.0.1:5000/api/holiday/
Authorization: Bearer {{admin_token}}

###

### 📅 Cập nhật ngày nghỉ //chưa xem
PUT http://127.0.0.1:5000/api/holiday/1
Content-Type: application/json
Authorization: Bearer {{admin_token}}

{
  "name": "Nghỉ 24",
  "start_date": "2028-06-30",
  "end_date": "2028-07-03"
}

###

### ❌ Xoá ngày nghỉ
DELETE http://127.0.0.1:5000/api/holiday/1
Authorization: Bearer {{admin_token}}

###

### 🌦️ Lấy cấu hình mùa hè admin //
GET http://127.0.0.1:5000/api/season/config?school_id=1
Authorization: Bearer {{admin_token}}

### 🌦️ Lấy cấu hình mùa hè trường
GET http://127.0.0.1:5000/api/season/config?school_id=1
Authorization: Bearer {{school_token}}

###

### 🛠️ Tạo cấu hình mùa hè
PUT  http://127.0.0.1:5000/api/season/config/?school_id=1
Content-Type: application/json
Authorization: Bearer {{admin_token}}

{
  "school_id": 1,
  "summer_start": "2025-06-01",
  "summer_end": "2025-09-30"
}

###

### 🕵️‍♂️ Check hôm nay có phải ngày nghỉ không?
GET http://127.0.0.1:5000/api/schedule-helper/is_holiday?device_id=2
Authorization: Bearer {{school_token}}

###

### 📆 Lấy lịch hôm nay
GET http://127.0.0.1:5000/api/schedule-helper/today
Authorization: Bearer {{school_token}}

###

### 📊 Thống kê hệ thống (admin)
GET http://127.0.0.1:5000/api/admin/stats
Authorization: Bearer {{admin_token}}
