"""Add winter_shift_config table

Revision ID: 13b7455f21f0
Revises: drop_season_config
Create Date: 2025-05-05 16:41:00.423466

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '13b7455f21f0'
down_revision = 'drop_season_config'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('season_config',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('school_id', sa.Integer(), nullable=False),
    sa.Column('summer_start', sa.Date(), nullable=False),
    sa.Column('summer_end', sa.Date(), nullable=False),
    sa.Column('winter_start', sa.Date(), nullable=True),
    sa.Column('winter_end', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('season_config')
    # ### end Alembic commands ###
