"""Add is_default column to bell_profiles

Revision ID: 17bb9b0ce367
Revises: aa5b4b947fbf
Create Date: 2025-05-04 18:15:13.110262

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '17bb9b0ce367'
down_revision = 'aa5b4b947fbf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bell_profiles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_default', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bell_profiles', schema=None) as batch_op:
        batch_op.drop_column('is_default')

    # ### end Alembic commands ###
