"""Add WinterShiftConfig and update SeasonConfig

Revision ID: 54c61cbe8675
Revises: af5b80cd8f76
Create Date: 2025-05-05 11:14:55.593453

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '54c61cbe8675'
down_revision = 'af5b80cd8f76'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('winter_shift_config',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('school_id', sa.Integer(), nullable=False),
    sa.Column('start_month', sa.Integer(), nullable=False),
    sa.Column('end_month', sa.Integer(), nullable=False),
    sa.Column('morning_shift_minutes', sa.Integer(), nullable=False),
    sa.Column('afternoon_shift_minutes', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('school_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('winter_shift_config')
    # ### end Alembic commands ###
