"""Add relationship between School and DisabledPeriod

Revision ID: 901cbc8b8383
Revises: 71d148317f24
Create Date: 2025-04-19 20:48:30.344809

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '901cbc8b8383'
down_revision = '71d148317f24'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('disabled_periods', schema=None) as batch_op:
        batch_op.add_column(sa.Column('description', sa.String(length=255), nullable=True))
        batch_op.drop_column('reason')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('disabled_periods', schema=None) as batch_op:
        batch_op.add_column(sa.Column('reason', sa.VARCHAR(length=200), nullable=True))
        batch_op.drop_column('description')

    # ### end Alembic commands ###
