"""Add school_id foreign key to bell_profiles

Revision ID: aa5b4b947fbf
Revises: add_foreign_key_school_id
Create Date: 2025-05-04 17:57:06.916146

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aa5b4b947fbf'
down_revision = 'add_foreign_key_school_id'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bell_profiles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('time_adjustment', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('description', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('school_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_bell_profiles_school_id', 'schools', ['school_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bell_profiles', schema=None) as batch_op:
        batch_op.drop_constraint('fk_bell_profiles_school_id', type_='foreignkey')
        batch_op.drop_column('school_id')
        batch_op.drop_column('description')
        batch_op.drop_column('time_adjustment')

    # ### end Alembic commands ###
