"""Add winter_start and winter_end to season_config

Revision ID: af5b80cd8f76
Revises: add_foreign_key_school_id
Create Date: 2025-05-05 10:50:51.590052

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'af5b80cd8f76'
down_revision = 'add_foreign_key_school_id'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('season_config', schema=None) as batch_op:
        batch_op.add_column(sa.Column('winter_start', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('winter_end', sa.Date(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('season_config', schema=None) as batch_op:
        batch_op.drop_column('winter_end')
        batch_op.drop_column('winter_start')

    # ### end Alembic commands ###
